// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcixfelzxcqbhhhebczh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjaXhmZWx6eGNxYmhoaGViY3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNDg0MDEsImV4cCI6MjA2ODcyNDQwMX0.PiWuw2x2axSmAMzrbwLggwStn3ryDvHrkfxeI_P9d98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});